'use client';
import {useEffect, useState} from 'react';
import {Tabs,TabsList,TabsTrigger,TabsContent} from '@/components/ui/tabs';
import {profiles,validTrack,type Track,type Profile} from './profiles';
import { ArrowUpRight, ArrowDown, CodeXml, Download, Code2 } from 'lucide-react';
function PortfolioBody({profile}:{profile:Profile}){return <>
<a className="skip" href="#main">Skip to content</a>

<main id="main"><section className="hero wrap"><div><p className="eyebrow"><span className="status-dot"/> OPEN TO {profile.role} OPPORTUNITIES</p><p className="intro">Hi, I’m Ribhu Pramanik.</p><h1>I build software.<br/><span>{profile.headline}</span></h1><p className="hero-description">{profile.description}</p><div className="actions"><a className="button primary" href="#work">Explore my work <ArrowDown size={17}/></a><a className="button secondary" href={profile.resume} download>Download {profile.label} CV <Download size={17}/></a></div><div className="hero-links"><a href="https://github.com/ribhupramanik">GitHub <ArrowUpRight size={15}/></a><a href="https://linkedin.com/in/ribhu-pramanik">LinkedIn <ArrowUpRight size={15}/></a><span>MCA · Chandigarh University</span></div></div>
<aside className="profile-panel" aria-label="Areas of work"><div className="panel-heading"><Code2 size={21}/><span>IDEAS → WORKING SOFTWARE</span><span className="panel-dot"/></div><div className="panel-main"><span className="panel-kicker">MY DEVELOPMENT FOCUS</span><h2>{profile.focusTitle}<br/>Made to be useful.</h2>{profile.focus.map(([title,description],i)=><div className="focus-row" key={title}><span>0{i+1}</span><div><strong>{title}</strong><p>{description}</p></div><ArrowUpRight size={19}/></div>)}</div><div className="panel-footer">{profile.stack.map(t=><span key={t}>{t}</span>)}</div></aside></section>
<section id="work" className="section wrap"><div className="section-heading"><div><p className="eyebrow">01 / SELECTED WORK</p><h2>Ideas put into practice<span>.</span></h2></div><p>{profile.workIntro}</p></div><div className="projects">{profile.projects.map(p=><article className="project" key={p.number}><div className="project-top"><span>{p.category}</span><span>{p.number}</span></div><h3>{p.name}</h3><p className="project-subtitle">{p.subtitle}</p><ol className="flow" aria-label={`${p.name} workflow`}>{p.steps.map((step,i)=><li key={step}><span>{i+1}</span>{step}</li>)}</ol><p>{p.description}</p><p className="project-detail">{p.detail}</p><ul className="tags" aria-label="Technologies">{p.stack.map(t=><li key={t}>{t}</li>)}</ul><a className="project-link" href={`https://github.com/ribhupramanik/${p.repo}`}><CodeXml size={17}/> Explore the code <ArrowUpRight size={17}/></a>{p.live && <a className="demo-link" href={p.live}>Open live demo <ArrowUpRight size={17}/></a>}</article>)}</div></section>
<section id="experience" className="section experience"><div className="wrap experience-grid"><div><p className="eyebrow">02 / EXPERIENCE</p><h2>Building beyond<br/>personal projects<span>.</span></h2><p className="section-description">Hands-on work across client applications, backend development, and Python automation.</p></div><div className="timeline">{[
['FEB 2026 — PRESENT','Freelance Software Developer','DigiBySR','Fixing production issues, implementing features, and improving workflows across client applications.'],
['OCT 2025 — FEB 2026','Tech Intern · Software Development','DigiBySR','Contributed to a Laravel warehouse management backend, role-based access control, inventory workflows, and Python automation scripts.'],
['OCT — NOV 2024','Software Developer Intern','Cofnifyze Technologies','Developed Python web scraping scripts, processed datasets, and assisted with API workflows, backend automation, and debugging.']
].map(([date,title,company,description])=><article key={title}><p className="job-meta">{date}</p><h3>{title}</h3><p className="company">{company}</p><p>{description}</p></article>)}</div></div></section>
<section id="about" className="section wrap"><div className="section-heading"><div><p className="eyebrow">03 / THE FOUNDATION</p><h2>Curiosity, backed by practice<span>.</span></h2></div></div><div className="about-grid"><div><h3>A developer who keeps learning.</h3><p>I’m pursuing my Master of Computer Applications at Chandigarh University while building my skills across AI, full stack development, and Laravel. I enjoy connecting data, backends, and interfaces to make applications people can use.</p><div className="education"><h4>Education</h4><p><strong>Master of Computer Applications</strong><span>Chandigarh University · 2025–Present</span></p><p><strong>Bachelor of Computer Applications</strong><span>Bengal School of Technology and Management · 2025 · 75.4%</span></p><p><strong>Diploma in CST</strong><span>Kalna Polytechnic · 2021 · 85.5%</span></p></div></div><div className="skills"><h3>My toolkit</h3>{profile.skillGroups.map(([title,skills])=><div key={title}><h4>{title}</h4><p>{skills}</p></div>)}<div className="certifications"><h4>Certifications</h4>{profile.certificates.map(c=>c.url?<a key={c.name} href={c.url}>{c.name}<ArrowUpRight size={17}/></a>:<p className="certificate" key={c.name}><strong>{c.name}</strong><span>{c.issuer}</span></p>)}</div></div></div></section>
<section className="contact wrap"><p className="eyebrow">HAVE A ROLE IN MIND?</p><h2>Let’s build something useful<span>.</span></h2><p>{profile.contact}</p><a className="contact-email" href="mailto:ribhu02@gmail.com">ribhu02@gmail.com <ArrowUpRight/></a><a className="button secondary" href={profile.resume} download><Download size={17}/> Download {profile.label} CV</a></section></main><footer className="footer wrap"><span>© 2026 Ribhu Pramanik</span><div><a href="https://github.com/ribhupramanik">GitHub</a><a href="https://linkedin.com/in/ribhu-pramanik">LinkedIn</a><a href="mailto:ribhu02@gmail.com">Email</a></div><a href="#">Back to top ↑</a></footer></>}


export default function Portfolio({initialTrack}:{initialTrack:Track}) {
 const [track,setTrack]=useState<Track>(initialTrack);
 useEffect(()=>{const sync=()=>setTrack(validTrack(new URL(window.location.href).searchParams.get('track'))); window.addEventListener('popstate',sync); return ()=>window.removeEventListener('popstate',sync)},[]);
 function selectTrack(value:unknown){const next=validTrack(value);setTrack(next);const url=new URL(window.location.href);if(next==='ai')url.searchParams.delete('track');else url.searchParams.set('track',next);url.hash='';window.history.pushState({},'',url)}
 return <div className="portfolio" data-theme={track}><header className="header wrap"><a className="wordmark" href="#" aria-label="Ribhu Pramanik home">rp<span>.</span></a><nav aria-label="Main navigation"><a href="#work">Work</a><a href="#experience">Experience</a><a href="#about">About</a></nav><a className="nav-contact" href="mailto:ribhu02@gmail.com">Let’s talk <ArrowUpRight size={17}/></a></header><Tabs value={track} onValueChange={selectTrack} className="portfolio-tabs"><div className="track-picker wrap"><p className="eyebrow">EXPLORE BY SPECIALIZATION</p><TabsList aria-label="Portfolio specialization" className="track-list">{(Object.keys(profiles) as Track[]).map(key=><TabsTrigger key={key} value={key} className="track-button"><span className={'track-dot '+key}/>{profiles[key].label}</TabsTrigger>)}</TabsList><p className="track-hint">Projects, skills, and a CV tailored to each focus.</p></div>{(Object.keys(profiles) as Track[]).map(key=><TabsContent key={key} value={key}><PortfolioBody profile={profiles[key]}/></TabsContent>)}</Tabs></div>
}
