export type Track = 'ai' | 'mern' | 'php';
export type Project = {number:string;category:string;name:string;subtitle:string;description:string;detail:string;stack:string[];repo:string;steps:string[];live?:string};
export type Profile = {label:string;role:string;headline:string;description:string;resume:string;focusTitle:string;focus:string[][];stack:string[];workIntro:string;projects:Project[];skillGroups:string[][];certificates:{name:string;issuer?:string;url?:string}[];contact:string};
export function validTrack(value:unknown):Track{return value==='mern'||value==='php'?value:'ai'}
const aiProjects: Project[] = [
 {number:'01',category:'GENERATIVE AI',name:'Hiring Assistant',subtitle:'A more structured first conversation.',description:'A conversational screening tool that collects candidate details and generates role-specific technical questions through a multi-stage interview workflow.',detail:'Structured prompts and session-based conversation management keep the interview context together.',stack:['Python','OpenAI API','Streamlit'],repo:'HiringAssistantChatbot',steps:['Candidate details','Technical questions','Contextual conversation']},
 {number:'02',category:'AI + DATA',name:'AI Report Maker',subtitle:'From data to a readable report.',description:'A Generative AI application for automated summarization, report generation, and structured content creation.',detail:'Combines Pandas data processing with LLM-powered workflows in a Streamlit interface.',stack:['Python','LangChain','Pandas','OpenAI API'],repo:'AI-ReportMaker',steps:['Structured datasets','Processing + summarization','Generated report']},
 {number:'03',category:'COMPUTER VISION',name:'Face & Mood Recognition',subtitle:'Computer vision, in real time.',description:'A desktop application that brings together face recognition and emotion analysis using OpenCV and DeepFace.',detail:'A Tkinter interface connects the recognition workflow with SQLite-based storage.',stack:['OpenCV','DeepFace','Tkinter','SQLite'],repo:'face-recognition-mood',steps:['Camera input','Face + emotion analysis','Desktop interface']}
];

export const profiles:Record<Track,Profile> = {
ai:{label:'Python & AI/ML',role:'AI/ML & PYTHON',headline:'With intelligence.',description:'Python developer focused on AI, machine learning, and practical automation. Turning ideas into LLM applications, computer vision tools, and better workflows.',resume:'/Ribhu-Pramanik-Resume.pdf',focusTitle:'Built with Python.',focus:[['Generative AI','LLM applications & structured prompts'],['Machine learning','Data, models & computer vision'],['Software development','Backends, APIs & automation']],stack:['Python','OpenAI','TensorFlow','SQL'],workIntro:'Three projects across language, data, and computer vision.',projects:aiProjects,skillGroups:[['AI & machine learning','TensorFlow · Scikit-learn · LangChain · OpenAI API · Prompt engineering · OpenCV'],['Data & development','Python · SQL · Pandas · NumPy · Streamlit · Git · Laravel']],certificates:[{name:'IBM Machine Learning',url:'https://coursera.org/share/9d086b1bd733c5ef884e658fe6877ffd'},{name:'TensorFlow Deep Learning',url:'https://www.udemy.com/certificate/UC-94a38cc4-66c6-4184-a5f8-baa03199dfe8/'},{name:'AI/ML & Data Science Bootcamp',url:'https://www.udemy.com/certificate/UC-e23e35c4-0efd-4146-a5fd-f8d2e7f82c72/'}],contact:'I’m interested in Python development, AI/ML, and Generative AI opportunities.'},
mern:{label:'MERN Stack',role:'MERN & FULL STACK',headline:'From API to interface.',description:'Backend-focused full stack developer building web applications with MongoDB, Express, React, and Node.js. Connecting secure APIs, authentication, and reusable interfaces.',resume:'/Ribhu-Pramanik-MERN-Resume.pdf',focusTitle:'Built with MERN.',focus:[['React interfaces','Reusable components & responsive UI'],['Node.js & Express','REST APIs & JWT authentication'],['MongoDB','Data models, filtering & search']],stack:['MongoDB','Express','React','Node.js'],workIntro:'Full stack projects across commerce, social media, and personal productivity.',projects:[
{number:'01',category:'ECOMMERCE',name:'MERN Ecommerce',subtitle:'From discovery to checkout.',description:'A full stack ecommerce platform with user authentication, shopping cart functionality, and protected checkout routes.',detail:'JWT authentication protects account workflows, while MongoDB query-based APIs support product filtering and search.',stack:['React','Node.js','Express','MongoDB','JWT'],repo:'MERN-Ecommerce',live:'https://mern-ecommerce-6gnq.onrender.com',steps:['Product search & filtering','Shopping cart','Protected checkout']},
{number:'02',category:'SOCIAL APPLICATION',name:'MERN Twitter Clone',subtitle:'Posts, profiles, and connections.',description:'A social media application with post creation, a follow system, and user profile management.',detail:'Protected routes and authorization middleware work alongside MongoDB schemas for posts, likes, and comments.',stack:['React','Node.js','Express','MongoDB','JWT'],repo:'Mern-Twitter-Clone',live:'https://mern-twitter-clone-q6p5.onrender.com',steps:['Authenticated profile','Posts & comments','Follow connections']},
{number:'03',category:'PRODUCTIVITY',name:'Notes Management App',subtitle:'A secure place for everyday notes.',description:'A notes management platform supporting full create, read, update, and delete operations.',detail:'JWT authentication and role-based access control secure the application, with modular React components for the interface.',stack:['React','Node.js','Express','MongoDB','RBAC'],repo:'Notes-App',steps:['Sign in','Create & organize notes','Update or delete']}
],skillGroups:[['MERN stack','JavaScript · React.js · Node.js · Express.js · MongoDB'],['Web development','REST APIs · JWT · MVC · MySQL · Laravel · Python · Git · HTML · CSS · Tailwind']],certificates:[{name:'Web Development Course',issuer:'Internshala'},{name:'Advanced Data Analytics',issuer:'Webel Fujisoft Vara'}],contact:'I’m interested in MERN, backend, and full stack development opportunities.'},
php:{label:'PHP & Laravel',role:'PHP & LARAVEL',headline:'Built around workflows.',description:'Backend-focused full stack developer building Laravel applications with PHP, MySQL, and JavaScript. Working on role-based access, database-driven workflows, and reliable client applications.',resume:'/Ribhu-Pramanik-PHP-Resume.pdf',focusTitle:'Built with Laravel.',focus:[['Laravel backends','MVC architecture & REST APIs'],['Access control','Middleware, gates & role-based access'],['Business workflows','MySQL, AJAX & data management']],stack:['PHP','Laravel','MySQL','AJAX'],workIntro:'Laravel projects for restaurant operations, financial deals, and team tasks.',projects:[
{number:'01',category:'RESTAURANT OPERATIONS',name:'Restaurant Management',subtitle:'Reservations meet daily operations.',description:'A Laravel restaurant platform with reservation workflows and secure CRUD functionality for menu, order, and customer modules.',detail:'Booking and cart interfaces connect the customer journey with a MySQL-backed application.',stack:['PHP','Laravel','MySQL'],repo:'Resturant-Project',steps:['Menu & customers','Booking & cart','Order management']},
{number:'02',category:'BUSINESS APPLICATION',name:'Financial Deal Management',subtitle:'Keep the deal lifecycle in view.',description:'A Laravel application with separate Admin and User dashboards for deal lifecycle workflows and payment tracking.',detail:'Includes PDF exports, AJAX filters, and secure Excel bulk uploads.',stack:['Laravel 12','AJAX','jQuery','MySQL'],repo:'Deal-Management',steps:['Admin & user dashboards','Deals & payment tracking','Uploads & PDF exports']},
{number:'03',category:'TEAM PRODUCTIVITY',name:'Task Management',subtitle:'Clear assignments. Connected updates.',description:'A multi-role task management system with task assignment and workflow status handling.',detail:'Laravel middleware and gates manage permissions, while AJAX supports comments and updates.',stack:['Laravel 12','AJAX','MySQL','RBAC'],repo:'Task-Management',steps:['Role-based access','Task assignment','Status & comments']}
],skillGroups:[['PHP & backend','PHP · Laravel · MySQL · REST APIs · RBAC · MVC'],['Web development','JavaScript · AJAX · jQuery · JWT · Python · Git · HTML · CSS · Tailwind']],certificates:[{name:'Laravel Course',issuer:'Ejob India'},{name:'Web Development Course',issuer:'Internshala'},{name:'Advanced Data Analytics',issuer:'Webel Fujisoft Vara'}],contact:'I’m interested in PHP, Laravel, and backend development opportunities.'}
};
